/**
 * AI Job Hunter — autonomous job search and application platform.
 * Developed by Lulamile Mkhungela.
 */
/**
 * Application generation.
 *
 * Builds a job-specific application package using ONLY facts from the CV:
 * tailored CV content, cover letter, short introduction, and answers to the
 * questions the advert asks. Any question that cannot be answered truthfully from
 * the CV is marked `needsUser` — the application then waits for the user instead of
 * guessing. Generated prose is validated by the truth guard.
 */
import { validate } from './truthGuard.js';
import { extractSkills, normaliseText, SKILL_BY_ID, resolveRole } from './skillTaxonomy.js';
import { complete, available as llmAvailable } from './llm.js';
import { logger } from '../lib/logger.js';

const log = logger('generator');

export function generateApplication({ profile, truthIndex, job, match, settings = {}, userId = null }) {
  const role = resolveRole(job.title) || resolveRole((settings.roles || [])[0]);
  const jobSkills = extractSkills(`${job.title}\n${job.description || ''}`, { limit: 40 }).map((s) => s.id);
  const cvSkillIds = new Set((truthIndex.skillIds || []).map(String));

  const relevantSkills = orderByRelevance(profile.skills || [], jobSkills);
  const relevantTools = orderByRelevance(
    (profile.skills || []).filter((s) => s.category === 'tool'),
    jobSkills
  );
  const relevantExperience = rankExperience(profile.experience || [], jobSkills);
  const relevantProjects = rankProjects(profile.projects || [], jobSkills);
  const relevantAchievements = rankAchievements(profile.achievements || [], jobSkills);

  const tailoredCv = {
    header: {
      name: profile.fullName,
      headline: profile.headline,
      email: profile.email,
      phone: profile.phone,
      location: profile.location,
      linkedin: profile.linkedinUrl,
      portfolio: profile.portfolioUrl,
      github: profile.githubUrl,
    },
    target: { title: job.title, company: job.company },
    summary: composeSummary({ profile, job, role, jobSkills, relevantSkills }),
    coreSkills: relevantSkills.slice(0, 14).map((s) => s.label || s),
    tools: relevantTools.slice(0, 10).map((s) => s.label || s),
    experience: relevantExperience.map((e) => ({
      title: e.title,
      company: e.company,
      location: e.location,
      startDate: e.startDate,
      endDate: e.endDate,
      current: e.current,
      highlights: e.highlights.slice(0, 4),
      description: e.description,
    })),
    education: profile.education || [],
    certifications: profile.certifications || [],
    projects: relevantProjects.slice(0, 3),
    languages: profile.languages || [],
    yearsExperience: profile.yearsExperience,
  };

  const coverLetter = composeCoverLetter({
    profile,
    job,
    match,
    settings,
    relevantSkills: tailoredCv.coreSkills,
    achievements: relevantAchievements,
    role,
  });

  const intro = composeIntro({ profile, job, relevantSkills: tailoredCv.coreSkills, achievements: relevantAchievements });

  const answers = buildAnswers({ profile, truthIndex, job, settings, cvSkillIds });

  // Truth guard on every generated string.
  // The target employer and role are legitimate to name; nothing else is added.
  const allow = [job.company, job.title, ...(job.company ? String(job.company).split(/\s+/) : [])].filter(Boolean);
  const guarded = {
    coverLetter: guard(coverLetter, truthIndex, 'cover letter', allow),
    intro: guard(intro, truthIndex, 'introduction', allow),
    summary: guard(tailoredCv.summary, truthIndex, 'CV summary', allow),
    answers: answers.map((a) => (a.autoGenerated ? { ...a, answer: guard(a.answer, truthIndex, `answer: ${a.question}`, allow).text } : a)),
  };

  const unresolved = guarded.answers.filter((a) => a.needsUser).map((a) => a.question);
  const needsUserInput = [
    ...unresolved,
    ...(guarded.coverLetter.violations.some((v) => v.type === 'unverified_years' || v.type === 'unverified_seniority')
      ? ['Some generated statements about experience were withheld — please review the draft.']
      : []),
  ];

  return {
    intro: guarded.intro.text,
    coverLetter: guarded.coverLetter.text,
    coverLetterSubject: `Application for ${job.title}${job.company ? ` — ${job.company}` : ''}`,
    tailoredCv: { ...tailoredCv, summary: guarded.summary.text },
    answers: guarded.answers,
    salaryExpectation: profile.salaryExpectation || null,
    salaryCurrency: profile.salaryCurrency || settings.currency || null,
    noticePeriod: profile.noticePeriod || null,
    relevantSkills: tailoredCv.coreSkills,
    relevantProjects,
    relevantAchievements,
    needsUserInput: [...new Set(needsUserInput)],
    truthGuard: (() => {
      const violations = [...guarded.coverLetter.violations, ...guarded.intro.violations, ...guarded.summary.violations];
      return { ok: violations.length === 0, violations };
    })(),
    engine: llmAvailable(userId) ? 'llm+deterministic' : 'deterministic',
    generatedAt: new Date().toISOString(),
  };
}

/** Optional LLM polish. Called by the pipeline for higher-quality prose when configured. */
export async function polishCoverLetter({ draft, profile, job, truthIndex, userId = null }) {
  if (!llmAvailable(userId)) return draft;
  const text = await complete({
    userId,
    system:
      'You are an expert career writer. Rewrite the cover letter draft so it flows naturally and stays under 320 words. ' +
      'Use ONLY the facts in the draft and the candidate facts list. Never add employers, qualifications, certifications, ' +
      'tools, job titles, metrics or years of experience that are not present. Do not add placeholders.',
    prompt: `CANDIDATE FACTS (do not exceed):\n${JSON.stringify(
      {
        name: truthIndex.name,
        titles: truthIndex.titles,
        companies: truthIndex.companies,
        skills: truthIndex.skillLabels,
        years: truthIndex.yearsExperience,
        seniority: truthIndex.seniority,
        education: truthIndex.education,
        certifications: truthIndex.certifications,
        achievements: truthIndex.achievements?.slice(0, 6),
      },
      null,
      1
    )}\n\nJOB: ${job.title} at ${job.company}\n\nDRAFT:\n${draft}\n\nReturn only the rewritten letter.`,
    maxTokens: 700,
  });
  if (!text) return draft;
  const check = validate(text, truthIndex, { allow: [job?.company, job?.title].filter(Boolean) });
  if (!check.ok) {
    log.warn('LLM polish rejected by truth guard — keeping deterministic draft', {
      violations: check.violations.map((v) => v.type),
    });
    return draft;
  }
  return text.trim();
}

/* ------------------------------------------------------------------ *
 * Composition
 * ------------------------------------------------------------------ */

function composeSummary({ profile, job, role, jobSkills, relevantSkills }) {
  const name = profile.fullName?.split(' ')[0] || 'I';
  const seniority = role?.label || profile.headline || profile.jobTitles?.[0] || 'design professional';
  const years = profile.yearsExperience;
  const yearsPhrase = years ? `${formatYears(years)} years' experience` : 'hands-on experience';
  const topSkills = relevantSkills.slice(0, 5).map((s) => s.label || s);
  const industries = (profile.industries || []).slice(0, 2);
  const achievement = (profile.achievements || []).find((a) => typeof a === 'object' && a.quantified)?.text;

  const sentences = [
    `${seniority} with ${yearsPhrase} across ${industries.length ? industries.join(' and ') : 'digital product teams'}.`,
    topSkills.length ? `Core strengths: ${listPhrase(topSkills)}.` : null,
  ].filter(Boolean);

  // The CV's own summary line is kept only when it adds something new.
  const cvSummaryLine = profile.summary ? firstSentences(profile.summary, 1) : null;
  if (cvSummaryLine && !overlaps(cvSummaryLine, sentences[0] || '')) sentences.push(cvSummaryLine);
  if (achievement) sentences.push(`Recent impact: ${achievement.replace(/\.$/, '')}.`);

  return dedupeSentences(sentences).join(' ').slice(0, 700);
}

function composeCoverLetter({ profile, job, match, settings, relevantSkills, achievements, role }) {
  const greeting = 'Dear Hiring Manager,';
  const firstName = profile.fullName?.split(' ')[0] || '';
  const roleLabel = role?.label || job.title;
  const company = job.company || 'your team';
  const years = profile.yearsExperience;
  const yearsPhrase = years ? `${formatYears(years)} years` : 'several years';
  const strong = (match?.strongMatches || []).slice(0, 5);
  const gaps = (match?.gaps || []).slice(0, 2);
  const topAchievement = achievements.find((a) => a.quantified)?.text || achievements[0]?.text;
  // Never repeat the same result twice in one letter (many CVs restate achievements
  // in both the summary and the role bullets).
  const secondAchievement = achievements.find((a) => a.quantified && a.text !== topAchievement && !overlaps(a.text, topAchievement))?.text;

  const p1 =
    `I'm applying for the ${job.title} role at ${company}. ` +
    `I'm a ${roleLabel} with ${yearsPhrase} of experience` +
    `${profile.industries?.length ? ` in ${listPhrase(profile.industries.slice(0, 2))}` : ''}, and the requirements in your advert line up closely with the work I do day to day.`;

  const p2Parts = [];
  if (strong.length) p2Parts.push(`The areas that overlap most directly are ${listPhrase(strong)}.`);
  const extraSkills = relevantSkills.filter((skill) => !strong.some((s) => s.toLowerCase() === String(skill).toLowerCase())).slice(0, 4);
  if (extraSkills.length) p2Parts.push(`I also work regularly in ${listPhrase(extraSkills)}.`);
  if (profile.experience?.[0]?.title && profile.experience?.[0]?.company) {
    const latest = profile.experience[0];
    p2Parts.push(`Most recently, as ${article(latest.title)} at ${latest.company}, ${latestDescriptionSentence(latest)}`);
  }
  const p2 = p2Parts.join(' ');

  const p3Parts = [];
  if (topAchievement) p3Parts.push(`A result I'm proud of: ${lowerFirst(topAchievement.replace(/\.$/, ''))}.`);
  if (secondAchievement) p3Parts.push(`I also ${lowerFirst(secondAchievement.replace(/\.$/, ''))}.`);
  if (!p3Parts.length && profile.projects?.length) {
    const project = profile.projects[0];
    p3Parts.push(`I recently worked on ${project.name}${project.description ? ` — ${lowerFirst(project.description.slice(0, 180))}` : ''}.`);
  }
  const p3 = p3Parts.join(' ');

  const p4 = gaps.length
    ? `If it's useful, I'd be glad to talk through where I'd ramp up quickly — ${listPhrase(gaps.map(softLower))} ${
        gaps.length === 1 ? 'is an area' : 'are areas'
      } I'd approach with a structured plan.`
    : `I'd welcome the chance to talk through how I can help ${company} with this work.`;

  const availability = [
    profile.noticePeriod ? `I can start ${/immediately/i.test(profile.noticePeriod) ? 'immediately' : `after ${profile.noticePeriod.replace(/^notice period[:\s]*/i, '')}`}.` : null,
    profile.workAuthorization ? `Work authorisation: ${profile.workAuthorization}.` : null,
  ].filter(Boolean);

  const closing = availability.length
    ? availability.join(' ')
    : 'I can make myself available for an interview at short notice.';

  const signoff = ['Kind regards,', profile.fullName || firstName || '', profile.phone, profile.email, profile.portfolioUrl, profile.linkedinUrl]
    .filter(Boolean)
    .join('\n');

  return [greeting, p1, p2, p3, p4, closing, signoff].filter((s) => s && s.trim()).join('\n\n');
}

function composeIntro({ profile, job, relevantSkills, achievements }) {
  const roleLabel = profile.headline || profile.jobTitles?.[0] || 'Designer';
  const years = profile.yearsExperience;
  const yearsPhrase = years ? `${formatYears(years)} years' experience` : 'hands-on experience';
  const top = achievements.find((a) => a.quantified)?.text;
  return [
    `${roleLabel} with ${yearsPhrase}${profile.industries?.length ? ` in ${listPhrase(profile.industries.slice(0, 2))}` : ''}.`,
    relevantSkills.length ? `Focused on ${listPhrase(relevantSkills.slice(0, 5))}.` : '',
    job.title ? `Applying for ${job.title}${job.company ? ` at ${job.company}` : ''}.` : '',
    top ? `Recent highlight: ${top.replace(/\.$/, '')}.` : '',
  ]
    .filter(Boolean)
    .join(' ')
    .slice(0, 500);
}

/* ------------------------------------------------------------------ *
 * Answers
 * ------------------------------------------------------------------ */

const QUESTION_RULES = [
  {
    id: 'right_to_work',
    test: /(right to work|work (?:authoris|authoriz)ation|legally (?:able|permitted) to work|eligible to work|work permit|visa status)/i,
    build: ({ profile, truthIndex }) => {
      const value = profile.workAuthorization || truthIndex.workAuthorization;
      return value
        ? { answer: `Yes — ${value}.`, source: 'cv', needsUser: false }
        : { answer: '', source: 'missing', needsUser: true };
    },
  },
  {
    id: 'sponsorship',
    test: /(require|need).{0,20}(sponsor|visa support)/i,
    build: ({ profile }) => {
      const auth = profile.workAuthorization;
      if (auth && /(no sponsorship|do not require|no visa|citizen|permanent resident|unrestricted)/i.test(auth)) {
        return { answer: 'No, I do not require sponsorship.', source: 'cv', needsUser: false };
      }
      return { answer: '', source: 'missing', needsUser: true };
    },
  },
  {
    id: 'notice_period',
    test: /notice period|when (?:can|could) you start|availability to start|earliest start date/i,
    build: ({ profile }) =>
      profile.noticePeriod
        ? { answer: `My notice period is ${profile.noticePeriod.replace(/^notice period[:\s]*/i, '')}.`, source: 'cv', needsUser: false }
        : { answer: '', source: 'missing', needsUser: true },
  },
  {
    id: 'salary',
    test: /salary (?:expectation|requirement|range)|expected (?:salary|remuneration|ctc)|remuneration expectation|package expectation/i,
    build: ({ profile }) =>
      profile.salaryExpectation
        ? { answer: `My expectation is ${profile.salaryExpectation}${profile.salaryCurrency ? ` (${profile.salaryCurrency})` : ''}, and I'm open to discussing the full package.`, source: 'cv', needsUser: false }
        : { answer: '', source: 'missing', needsUser: true },
  },
  {
    id: 'years_specific',
    test: /how many years.{0,40}(?:experience|worked).{0,30}with\s+([a-z0-9+#. /-]{2,30})/i,
    build: ({ profile, truthIndex, cvSkillIds, match }) => {
      const skill = match[1]?.trim();
      const ids = extractSkills(skill || '', { limit: 2 }).map((s) => s.id);
      const has = ids.some((id) => cvSkillIds.has(id)) || (skill && (truthIndex.declaredSkills || []).some((d) => normaliseText(d) === normaliseText(skill)));
      if (has && profile.yearsExperience) {
        return {
          answer: `I've used ${skill} throughout my ${formatYears(profile.yearsExperience)} years of professional experience — most recently in my current role.`,
          source: 'cv',
          needsUser: false,
        };
      }
      if (has) return { answer: `Yes — ${skill} is part of my day-to-day work, as shown in my CV.`, source: 'cv', needsUser: false };
      return { answer: '', source: 'missing', needsUser: true, note: `${skill} is not on the CV — answer honestly or skip this role.` };
    },
  },
  {
    id: 'why_company',
    test: /why (?:do you want|would you like) to (?:work|join)|why are you interested in (?:this|the) (?:role|position|company)/i,
    build: ({ job, profile }) => ({
      answer:
        `The ${job.title} role lines up with the work I do and want to keep doing. ` +
        `${job.company ? `${job.company}'s ` : 'Your '}focus on ${describeFocus(job)} matches the problems I find most interesting` +
        `${profile.industries?.length ? `, and it sits in the ${profile.industries[0]} space I've worked in` : ''}. ` +
        `I'd bring the practical experience described in my CV and a collaborative, evidence-led approach.`,
      source: 'generated_from_cv',
      needsUser: false,
    }),
  },
  {
    id: 'remote_ok',
    test: /(comfortable|happy|able|willing) (?:to |with )?(?:work )?(?:fully )?remote|remote work (?:ok|fine|acceptable)/i,
    build: () => ({ answer: 'Yes — I work effectively in remote and hybrid setups and am comfortable with distributed collaboration.', source: 'profile_preference', needsUser: false }),
  },
  {
    id: 'onsite_ok',
    test: /(able|willing|comfortable) to (?:work )?(?:on-?site|in the office|in-office)|onsite (?:ok|fine)/i,
    build: () => ({ answer: '', source: 'missing', needsUser: true, note: 'In-office availability depends on your location preference — confirm before submitting.' }),
  },
  {
    id: 'portfolio',
    test: /(portfolio|work samples|case stud)/i,
    build: ({ profile }) =>
      profile.portfolioUrl || profile.linkedinUrl
        ? { answer: `Yes — my portfolio is available at ${profile.portfolioUrl || profile.linkedinUrl}.`, source: 'cv', needsUser: false }
        : { answer: '', source: 'missing', needsUser: true, note: 'No portfolio URL on the CV — add one in your profile.' },
  },
  {
    id: 'expected_start',
    test: /(available to start|start date)/i,
    build: ({ profile }) =>
      profile.noticePeriod
        ? { answer: `Available to start ${/immediately/i.test(profile.noticePeriod) ? 'immediately' : `once I serve my ${profile.noticePeriod.replace(/^notice period[:\s]*/i, '')} notice period`}.`, source: 'cv', needsUser: false }
        : { answer: '', source: 'missing', needsUser: true },
  },
  {
    id: 'degree_required',
    test: /(do you (?:have|hold)|have you (?:completed|obtained)).{0,40}(degree|diploma|qualification|bachelor|bsc)/i,
    build: ({ profile }) =>
      profile.education?.length
        ? { answer: `Yes — ${profile.education[0].qualification}${profile.education[0].institution ? ` from ${profile.education[0].institution}` : ''}.`, source: 'cv', needsUser: false }
        : { answer: '', source: 'missing', needsUser: true, note: 'No qualification is stated on the CV.' },
  },
];

export function buildAnswers({ profile, truthIndex, job, cvSkillIds }) {
  const questions = [];
  // Questions can arrive from the source connector (requirements.questions), from a
  // manual/copied advert, or from a guided connector's handoff — all three are accepted.
  const explicit = job.requirements?.questions || job.questions || job.apply?.questions || [];
  for (const q of explicit) questions.push({ question: String(q.question || q), required: q.required !== false });
  // Fall back to questions phrased inside the advert text.
  if (!questions.length) {
    const text = job.description || '';
    const candidates = text.match(/[^?\n]{12,160}\?/g) || [];
    for (const c of candidates.slice(0, 8)) {
      if (/(you|your|do you|have you|are you|can you|will you)/i.test(c)) questions.push({ question: c.trim(), required: false });
    }
  }

  const answers = questions.slice(0, 10).map((q) => {
    const rule = QUESTION_RULES.find((r) => r.test.test(q.question));
    if (!rule) {
      return {
        question: q.question,
        answer: '',
        source: 'missing',
        needsUser: true,
        autoGenerated: false,
        note: 'Not answerable from the CV — answer this yourself.',
      };
    }
    const built = rule.build({ profile, truthIndex, cvSkillIds, job, match: rule.test.exec(q.question) || [] });
    return {
      question: q.question,
      answer: built.answer,
      source: built.source,
      needsUser: !!built.needsUser,
      note: built.note || null,
      autoGenerated: !!built.answer,
      rule: rule.id,
    };
  });

  // Always give the user the standing answers they may need.
  if (!answers.some((a) => a.rule === 'salary') && profile.salaryExpectation) {
    answers.push({ question: 'Salary expectation (if asked)', answer: `My expectation is ${profile.salaryExpectation}.`, source: 'cv', needsUser: false, autoGenerated: true, rule: 'salary' });
  }
  if (!answers.some((a) => a.rule === 'notice_period') && profile.noticePeriod) {
    answers.push({ question: 'Notice period (if asked)', answer: `My notice period is ${profile.noticePeriod.replace(/^notice period[:\s]*/i, '')}.`, source: 'cv', needsUser: false, autoGenerated: true, rule: 'notice_period' });
  }
  for (const a of answers) repairBoolean(a);
  return answers;
}

function repairBoolean(a) {
  if (typeof a.autoGenerated === 'string') a.autoGenerated = a.autoGenerated === 'true';
  return a;
}

function describeFocus(job) {
  const skills = extractSkills(`${job.title}\n${job.description || ''}`, { limit: 3 }).map((s) => s.label);
  if (skills.length) return listPhrase(skills.map((s) => s.toLowerCase()));
  return 'building products that solve real user problems';
}

/* ------------------------------------------------------------------ *
 * Helpers
 * ------------------------------------------------------------------ */

function guard(text, truthIndex, label, allow = []) {
  const result = validate(text, truthIndex, { allow });
  if (!result.ok) log.warn(`truth guard flagged ${label}`, { violations: result.violations.map((v) => v.type) });
  return result;
}

function orderByRelevance(skills, jobSkillIds) {
  const wanted = new Set(jobSkillIds);
  return [...skills].sort((a, b) => {
    const aScore = (wanted.has(a.id) ? 10 : 0) + (a.hits || 0) + (a.category === 'tool' ? 0.5 : 0);
    const bScore = (wanted.has(b.id) ? 10 : 0) + (b.hits || 0) + (b.category === 'tool' ? 0.5 : 0);
    return bScore - aScore;
  });
}

function rankExperience(experience, jobSkillIds) {
  const wanted = new Set(jobSkillIds);
  return experience.map((e, index) => {
    const text = extractSkills(`${e.title} ${(e.highlights || []).join(' ')} ${e.description || ''}`, { limit: 20 });
    const relevance = text.filter((s) => wanted.has(s.id)).length;
    return { ...e, relevance, recencyIndex: index };
  }).sort((a, b) => {
    if (a.current !== b.current) return a.current ? -1 : 1;
    if (b.relevance !== a.relevance) return b.relevance - a.relevance;
    return a.recencyIndex - b.recencyIndex;
  });
}

function rankProjects(projects, jobSkillIds) {
  const wanted = new Set(jobSkillIds);
  return projects.map((p) => ({
    ...p,
    relevance: extractSkills(`${p.name} ${p.description || ''}`, { limit: 10 }).filter((s) => wanted.has(s.id)).length,
  })).sort((a, b) => b.relevance - a.relevance);
}

function rankAchievements(achievements, jobSkillIds) {
  const wanted = new Set(jobSkillIds);
  const normalised = achievements.map((a) => (typeof a === 'string' ? { text: a, quantified: /\d/.test(a) } : a));
  return normalised
    .map((a) => ({ ...a, relevance: extractSkills(a.text, { limit: 8 }).filter((s) => wanted.has(s.id)).length }))
    .sort((a, b) => b.relevance - a.relevance || Number(b.quantified) - Number(a.quantified));
}

function latestDescriptionSentence(experience) {
  const highlight = (experience.highlights || [])[0];
  if (highlight) return `I ${lowerFirst(highlight.replace(/\.$/, ''))}.`;
  if (experience.description) return firstSentences(experience.description, 1);
  return `I worked across ${listPhrase(extractSkills(`${experience.title}`, { limit: 3 }).map((s) => s.label.toLowerCase())) || 'the full product lifecycle'}.`;
}

function firstSentences(text = '', count = 1) {
  const parts = String(text).split(/(?<=[.!?])\s+/).filter(Boolean);
  return parts.slice(0, count).join(' ');
}

/** True when two bullets say substantially the same thing. */
function overlaps(a = '', b = '') {
  const na = normaliseText(a);
  const nb = normaliseText(b);
  if (!na || !nb) return false;
  if (na.includes(nb) || nb.includes(na)) return true;
  const wordsA = new Set(na.split(' ').filter((w) => w.length > 3));
  const wordsB = nb.split(' ').filter((w) => w.length > 3);
  if (!wordsA.size || !wordsB.length) return false;
  const shared = wordsB.filter((w) => wordsA.has(w)).length;
  return shared / Math.max(wordsA.size, wordsB.length) > 0.5;
}

function dedupeSentences(sentences) {
  const seen = new Set();
  return sentences.filter((s) => {
    const key = normaliseText(s).slice(0, 60);
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function listPhrase(items = []) {
  const clean = items.filter(Boolean);
  if (!clean.length) return '';
  if (clean.length === 1) return clean[0];
  if (clean.length === 2) return `${clean[0]} and ${clean[1]}`;
  return `${clean.slice(0, -1).join(', ')} and ${clean[clean.length - 1]}`;
}

function formatYears(value) {
  const n = Number(value);
  if (!Number.isFinite(n)) return '';
  if (n >= 1) return String(Math.floor(n * 10) / 10).replace(/\.0$/, '');
  return String(Math.max(0.5, Math.round(n * 10) / 10));
}

function article(word = '') {
  return `${/^[aeiou]/i.test(word) ? 'an' : 'a'} ${word}`;
}

function lowerFirst(s = '') {
  return s ? s.charAt(0).toLowerCase() + s.slice(1) : s;
}

const ACRONYMS = /\b[A-Z]{2,}\b/;
const PROPER_TOOLS = /\b(Figma|Sketch|React|Vue|Angular|Svelte|Python|Java|JavaScript|TypeScript|Photoshop|Illustrator|InDesign|After Effects|Miro|Storybook|Tailwind|Bootstrap|Webflow|Canva|Zeplin|Framer|WordPress|Shopify|Jira|Confluence|Notion|Luno|Google|Adobe|Figma|Dovetail|Maze|Hotjar)\b/;

/**
 * Lower-cases a title-cased phrase for mid-sentence use without mangling acronyms
 * ("Motion & Animation" -> "motion & animation", "UX Research" stays "UX Research").
 */
function softLower(phrase = '') {
  const value = String(phrase);
  if (ACRONYMS.test(value) || PROPER_TOOLS.test(value)) return value;
  if (/^([A-Z][a-z']+(?: &)?\s?)+[A-Z][a-z']+$/.test(value)) return value.toLowerCase();
  return lowerFirst(value);
}

export { SKILL_BY_ID };
